# Generated by Django 6.0.6 on 2026-09-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author_delete_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='reparation_time_unit',
            new_name='preparation_time_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='uptaded_at',
            new_name='updated_at',
        ),
    ]
